config/routes.rb
Rails.application.routes.draw do
 

  devise_for :authors

  namespace :authors do
    resources :posts
  end

  scope module: 'blog' do
    get "about", to: "pages#about", as: :about
    get "contacts", to: "pages#contacts", as: :contacts
    get "posts", to: "posts#index", as: :posts
    get "posts/:id",  to: "posts#show", as: :post
  end

  root 'blog/pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, #:registerable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  scope :most_recent, -> {order( id: :desc)}

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    "Published #{created_at.strftime('%-b %-d, %Y')}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # layout 'author'
end

app/controllers/author_controller.rb
  class AuthorController < ApplicationController
    before_action :authenticate_author!

    layout 'author'

  end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
  before_action :set_post, only: [:show, :update, :edit, :destroy]

    def index
      @post = Post.all
    end

    def show
    end

    def new
      @post = Post.new
    end

    def edit
      
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to posts_path
      else
        flash[:alert] = "Did not create. Something went wrong."
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to authors_posts_path
    end



  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :description)
    end

  end




end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < ApplicationController

    def home
    end

    def about
    end

    def contact
    end
  end
end

app/controllers/blog/posts_controller.rb
module Blog
	class PostsController < ApplicationController
		before_action :set_post, only: [:show, :update, :edit, :destroy]

		def index
			@post = Post.all
		end

		def show
			
		end

		def create
			@post = Post.create(post_params)
			if @post.save
				redirect_to posts_path
			end
		end

	private

			def set_post
				@post = Post.friendly.find(params[:id])
			end

			def post_params
				params.require(:post).permit(:title, :body, :description)
			end
			
	end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  # before_action :set_post, only: [:show, :update, :edit, :destroy]

  def index
    @post = Post.all
  end

  def show
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to posts_path
    end
  end



private
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/posts/_form.html.haml
= simple_form_for @post, url: authors_posts_path do |f|
  = f.input :title
  = f.input :description
  = f.input :body
  = f.submit "Create Post", class: "btn btn-primary"

app/views/authors/posts/index.html.haml
.container-fluid
  - @post.each do |post|
    .row.col-md-4.col-md-offset-1
      .panel.panel-default
        .panel-heading
          %h3
            = post.title
        .panel-body
          %h5.row
            = post.description
          .row
            = post.body
      =link_to "delete", authors_post_path(post), method: :delete

app/views/authors/posts/new.html.haml
- provide(:page_title, @post.title)

%h1 New Post


= render "form"

app/views/authors/posts/show.html.haml
provide(:page_title, @post.title)

%h1
  Show

app/views/blog/pages/home.haml
%h1 Home

app/views/blog/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :description
	= f.input :body
	= f.submit

app/views/blog/posts/index.html.haml
- @post.each do |post|
  .row.col-md-4
    %h3
      = post.title
    %h5.row
      = post.description
    .row
      = post.body

app/views/blog/posts/new.haml
- provide(:page_title, @post.title)

%h1 New Post

= render "form"

app/views/blog/posts/show.html.haml
provide(:page_title, @post.title)

%h1
  Show

app/views/layouts/_authors_navbar.haml
%nav.navbar.navbar-light.bg-faded
  %ul.nav.navbar-nav
    - if 
      %li
        = link_to "New Post", new_authors_post_path
      %li
        = link_to "Logout", destroy_author_session_path, method: :delete
    - else
      %li
        = link_to "Login", new_author_session

app/views/layouts/_navbar.haml
%nav.navbar.navbar-light.bg-faded
  %ul.nav.navbar-nav
    %li.nav-item.active
      = link_to "Home", root_path , class: "nav-link"
    %li.nav-item
      = link_to "Posts", posts_path , class: "nav-link"
    %li.nav-item
      = link_to "Contact", "" , class: "nav-link"
    %li.nav-item
      = link_to "About", "" , class: "nav-link"
    %li.nav-item
      = link_to "Authors", authors_posts_path , class: "nav-link"

app/views/layouts/application.haml
!!!
%html
%head
  %title
    = yield (:page_title)
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  = render "layouts/navbar"

  .row
    .col-md-6.col-md-offset-3
      = yield

app/views/layouts/author.haml
!!!
%html
%head
  %title
    = yield (:page_title)
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  = render "layouts/authors_navbar"
  %p.notice= notice
  %p.alert= alert

  .row
    .col-md-8.col-md-offset-2
      = yield 